
version: 2

models:
  - name: stg_events
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: event_name
        tests:
          - accepted_values:
              values:
                - page_view
                - add_to_cart
                - begin_checkout
                - purchase
                - signup

  - name: fct_sessions
    tests:
      - not_null:
          column_name: session_id

  - name: fct_funnels_signup
    columns:
      - name: consent_measurement
        tests:
          - accepted_values:
              values: [true]
              quote: false