
version: 2

models:
  - name: stg_events
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: consent_measurement
        tests:
          - not_null

  - name: fct_sessions
    tests:
      - not_null:
          column_name: session_id

  - name: fct_funnels_signup
    columns:
      - name: consent_measurement
        tests:
          - accepted_values:
              values: [true]
              quote: false
